imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
parameters:
    locale: en

framework:
    secret: 'donotuseinproduction'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: false
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
twig:
    form_themes:
        - bootstrap_3_layout.html.twig

old_sound_rabbit_mq:
    connections:
        default:
            host:     'rabbitmq'
            port:     5672
            user:     'rabbit'
            password: 'rabbit'
            vhost:    '/'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3

    producers:
        payment_producer:
            connection:       default
            exchange_options: {name: 'symfonyday', type: direct}
            queue_options:    {name: 'payment'}
            service_alias:    payment.producer

    consumers:
        payment_consumer:
            connection:       default
            exchange_options: {name: 'symfonyday', type: direct}
            queue_options:    {name: 'payment'}
            callback:         payment.consumer