imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
parameters:
    locale: en

framework:
    secret: 'donotuseinproduction'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: false
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
twig:
    form_themes:
        - bootstrap_3_layout.html.twig
